theme: jekyll-theme-cayman
title: 春川, Buffalo, 데이터 사이언스.
description:  Making sense of the big data world from a social scientist view.
description:  laguna821@gmail.com
show_downloads: false
google_analytics:
